version: '3.4'

services:
  databaseapi:
    image: ${DOCKER_REGISTRY-}databaseapi
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
    - 44313:443
    networks:
    - localhost
  pubsubapi:
    image: ${DOCKER_REGISTRY-}pubsubapi
    build:
      context: .
      dockerfile: PubSub/Dockerfile
    ports:
    - 8000:443
    links:
        - databaseapi
    networks:
    - localhost
  redis:
    image: redis
    ports:
        -  6379:6379
    networks:
    - localhost
networks:
  localhost:
    driver: bridge

